### ISSUE TITLE
Unknown which symbols do not return transcript

### ISSUE THREAD

**Issue by sandertan** [genome-nexus/genome-nexus#117]
When I call POST /ensembl/canonical-transcript/hgnc with these 4 symbols:
```
["TPR", "BRAF", "SANDER", "TP53"]
```
it returns only 3 transcripts. It's unclear for which symbol no transcript can be found.

Would it be possible to return the submitted symbol in the result?

@jjgao

**Comment by jjgao** [comment]
@sandertan good point.

**Comment by sandertan** [comment]
This has been fixed.
