### ISSUE TITLE
Overwrite VEP protein start/end for variant duplication

### ISSUE THREAD

**Issue by zhx828** [genome-nexus/genome-nexus#126]
This issue was brought up in OncoKB. In [the patient](http://www.cbioportal.org/case.do#/patient?sampleId=P-0007009-T02-IM5&studyId=msk_impact_2017),  the P68_C77dup is not annotated as Predicted Oncogenic but it has the overlap with the hotspot range 65-77indel.

The reason is that VEP annotates the AKT1 P68_C77dup with protein start and end both as 78.  Based on discussion/feedback from Niki and JJ, the position could also be 68, it depends on the caller.

JJ suggested that in the genome nexus, we should overwrite the protein start and end with 68 and 77.

**Comment by inodb** [comment]
Fixed in 1.12 by @onursumer http://www.cbioportal.org/beta/case.do#/patient?sampleId=P-0007009-T02-IM5&studyId=msk_impact_2017
