### ISSUE TITLE
investigate hotspot types

### ISSUE THREAD

**Issue by jjgao** [genome-nexus/genome-nexus#137]
For each cancer hotspot (http://cancerhotspots.org/#/home), let's find out the different types of mutations the hotspot was based on.

Starting from this spreadsheet (http://cancerhotspots.org/files/hotspots_v2.xls), add the following columns:

- fraction of missense mutations
- fraction of in-frame mutations (should be 100% for all inframe hotspots)
- fraction of nonsense mutations (*)
- fraction of splice mutations
- fraction of other types of mutations

Some of the hotspots should be excluded for matching missense mutations, for example ALK R401 is based on mostly non-sense mutations.

**Comment by inodb** [comment]
https://gist.github.com/inodb/5cb5f8ae90c05365bf73f19e6e64b732

https://docs.google.com/spreadsheets/d/1vzcw3jgNsxgya8B7RZTn2Vw_9_Iuuqkj10aCs-S662M/edit#gid=0

**Comment by inodb** [comment]
@jjgao ☝️ this is down now lmk when u have some time to review

**Comment by jjgao** [comment]
@onursumer @inodb @zhx828 we should also annotate splice mutations for the splice hotspots.

**Comment by jjgao** [comment]
we forgot to remove hotspots based on silent mutations, e.g MET T222T
