### ISSUE TITLE
in_frame_deletion issue

### ISSUE THREAD

**Issue by zhx828** [genome-nexus/genome-nexus#151]
PIK3CA V105_E109delinsG is annotated with proteinStart: 109 but it should be 105

https://cbioportal.mskcc.org/case.do?#/patient?sampleId=P-0022125-T01-IM6&studyId=mskimpact

**Comment by inodb** [comment]
@zhx828 @onursumer  The endpoint of the web service does return start pos of 105:

http://genomenexus.org/annotation/3%3Ag.178916927_%20178916939delTAGGCAACCGTGAinsG?fields=hotspots

So maybe the data needs to be updated? Or could be problem in the annotator. Will check

**Comment by inodb** [comment]
Hmm so looks like the annotator only outputs `Protein_position` not `Protein_start` and `Protein_end`. Does seem to fill in 105. So not sure where this start position came from.

Are you using this for OncoKB data @zhx828 ? For hotspots in 1.12 the mutations get annotated on the fly by genome nexus. So that should be fine

See:

https://cbioportal.mskcc.org/beta/case.do#/patient?sampleId=P-0022125-T01-IM6&studyId=mskimpact

**Comment by inodb** [comment]
So protein start and end in the database are determined by the importer: https://github.com/cBioPortal/cbioportal/blob/master/core/src/main/java/org/mskcc/cbio/portal/scripts/ImportExtendedMutationData.java#L266-L269

**Comment by zhx828** [comment]
@inodb protein sends proteinStart 109 to OncoKB for annotation, but it should be 105. Should I mark this as portal issue?

**Comment by inodb** [comment]
Issue is here: https://github.com/cBioPortal/cbioportal/blob/HEAD/core/src/main/java/org/mskcc/cbio/portal/util/ExtendedMutationUtil.java#L149-L150

When proteinPosition is missing it tries to determine it from the protein change in an incorrect manner

**Comment by inodb** [comment]
it will prolly be fixed when reannotating mskimpact and reimporting, since i do see proteinPosition being filled in. @angelicaochoa @ritikakundra could you do that?

**Comment by zhx828** [comment]
@inodb I will ask send a patch to fix the issue in portal avoiding the similar issue in the future.

**Comment by inodb** [comment]
sounds good thanks!

**Comment by zhx828** [comment]
The fix in portal is merged: https://github.com/cBioPortal/cbioportal/pull/4004

**Comment by inodb** [comment]
Fixed in genome nexus as well:

https://www.genomenexus.org/annotation/summary/3:g.178916927_178916939delTAGGCAACCGTGAinsG

Not sure about annotation pipeline

**Comment by inodb** [comment]
yup looks like annotation pipeline also gets correct `Protein_position`
