### ISSUE TITLE
Display and/or specify Ensembl Release and Reference Genome

### ISSUE THREAD

**Issue by sandertan** [genome-nexus/genome-nexus#156]
I was wondering if it will be possible to display and/or specify the Ensembl release and reference genome used.

**Comment by inodb** [comment]
@sandertan where? In cBioPortal or in the output from the API?

**Comment by sandertan** [comment]
@inodb Hi Ino, I think it would be useful to query the API for both hg19 and hg38. I understand this would be a lot of work to implement, but we sometimes hear that users would like hg38 for their cBioPortal data. Also, Kelsey is working on a PR to cBioPortal to support multiple reference genomes for mutations https://github.com/cBioPortal/cbioportal/pull/3703 .

Regarding the output, I can imagine it would be useful to display the used Ensembl Release and the reference genome. This would explain the context of the returned result.

**Comment by inodb** [comment]
Hi Sander,

Yeah we were thinking to run a hg38 instance as well at some point. Similar
to how ensembl has multiple instances. It would prolly just be passing some
parameter to genome-nexus-importer and setting some config for
genome-nexus. Then hg19 or hg38 would be in the URL.
