### ISSUE TITLE
Multiple Hugo Symbols per gene?

### ISSUE THREAD

**Issue by sandertan** [genome-nexus/genome-nexus#157]
I was wondering why `Hugo Symbols` is a list. Are there cases when 1 entry contains multiple symbols (not aliases)? I think according to HGNC (HUGO Gene Nomenclature Committee) these symbols should be unique. https://www.genenames.org Or does Ensembl add additional Symbols?

![screen shot 2018-03-28 at 14 49 23](https://user-images.githubusercontent.com/9624990/38029984-9e2c84ac-3297-11e8-9701-9c32f134e86d.png)

**Comment by inodb** [comment]
Hi @sandertan . This is based on the raw data dump from ensembl: https://github.com/genome-nexus/genome-nexus-importer/blob/master/data/Makefile#L6. There are cases where 1 transcript contains multiple symbols indeed.

We are actually working on making a new endpoint with single hugo to ensembl gene id mapping. See https://github.com/genome-nexus/genome-nexus/issues/150. This follows the hugo ensembl ids that were assigned in the https://www.genenames.org/ data dump. There are some gene symbols that don't have an assigned ensembl id, but none of those genes are super important for cbioportal purpose

**Comment by sandertan** [comment]
Thanks. Good to know!
