### ISSUE TITLE
cancerhotspots improvement

### ISSUE THREAD

**Issue by jjgao** [genome-nexus/genome-nexus#175]
Currently GN is caching annotation of cancerhotspots when querying a non-hotspot gene, which takes long time? Is it b/c VEP annotation is slow? Or cancer hotspot annotation?

**Comment by onursumer** [comment]
We don't use cancer hotspots service anymore, instead we import from a local file. Here is the latest Cancer Hotspots data file we import into the db: https://github.com/genome-nexus/genome-nexus-importer/blob/master/export/hotspots_v2_and_3d.txt
