### ISSUE TITLE
Add PFAM names and descriptions to the response of transcript web-services

### ISSUE THREAD

**Issue by pieterlukasse** [genome-nexus/genome-nexus#189]
Currently the transcript web-services return the following info:
```json
[
  {
    "transcriptId": "string",
    "geneId": "string",
    "proteinId": "string",
    "proteinLength": 0,
    "pfamDomains": [
      {
        "pfamDomainId": "string",
        "pfamDomainStart": 0,
        "pfamDomainEnd": 0
      }
    ],
    "exons": [
      {
        "exonId": "string",
        "exonStart": 0,
        "exonEnd": 0,
        "rank": 0,
        "strand": 0,
        "version": 0
      }
    ],
    "hugoSymbols": [
      "string"
    ]
  }
]
```
Would be nice if    ` "description": "string",    "name": "string",` could be added to `pfamDomains`: 
```json
    "pfamDomains": [
      {
        "pfamDomainId": "string",
        "pfamDomainStart": 0,
        "pfamDomainEnd": 0,
        "description": "string",
        "name": "string"
      }
    ],
```

**Comment by onursumer** [comment]
@pieterlukasse There is a separate endpoint for that, for example: http://genomenexus.org/pfam/domain/PF01030. 

The reason we left out the additional information here is to avoid duplication. You may have multiple segments for the same PFAM domain. Here is an example for that (`PF01030` has multiple segments):

```JavaScript
{
    "transcriptId": "ENST00000275493",
    "geneId": "ENSG00000146648",
    "hugoSymbols": [
      "EGFR"
    ],
    "proteinId": "ENSP00000275493",
    "proteinLength": 1210,
    "pfamDomains": [
      {
        "pfamDomainId": "PF00757",
        "pfamDomainStart": 185,
        "pfamDomainEnd": 338
      },
      {
        "pfamDomainId": "PF07714",
        "pfamDomainStart": 713,
        "pfamDomainEnd": 965
      },
      {
        "pfamDomainId": "PF14843",
        "pfamDomainStart": 505,
        "pfamDomainEnd": 636
      },
      {
        "pfamDomainId": "PF01030",
        "pfamDomainStart": 57,
        "pfamDomainEnd": 167
      },
      {
        "pfamDomainId": "PF01030",
        "pfamDomainStart": 361,
        "pfamDomainEnd": 480
      }
    ],
    ...
}
```

Adding the description and name into this response may unnecessarily increase the size of it. In cBioPortal, we are using the separate endpoint (http://genomenexus.org/pfam/domain) to get this additional information.

**Comment by pieterlukasse** [comment]
Ok, thanks @onursumer. Not sure if I agree with the size argument, since most proteins will have a limited number of domains...so it is not like we are talking about thousands of extra lines in the response (unless thousands of transcripts are queried at once using the POST endpoint - but perhaps the `projection` approach we use in cBioPortal API could solve this). Anyway, the design choice of using an extra endpoint sounds reasonable to me.

**Comment by pieterlukasse** [comment]
related to discussion in https://github.com/genome-nexus/genome-nexus/issues/197
