### ISSUE TITLE
Modeling PFAM domain

### ISSUE THREAD

**Issue by onursumer** [genome-nexus/genome-nexus#19]
_From @jjgao on October 17, 2016 15:28_

- [x] Build Java code to connect to BioMart to get domain coordinates
- [x] Data model of PFAM data in Genome Nexus

_Copied from original issue: cBioPortal/cbioportal#1813_

**Comment by jjgao** [comment]
@n1zea144 and @jjgao discussed: Maybe PFAM data can be separate just like PDB data. But later integrated into the Genome-Nexus web service (?).

**Comment by onursumer** [comment]
PFAM model from BioMart is introduced with #62
