### ISSUE TITLE
wrong hotspots

### ISSUE THREAD

**Issue by jjgao** [genome-nexus/genome-nexus#214]
reported here: https://github.com/oncokb/oncokb/issues/1343

Query: https://cbioportal.mskcc.org/index.do?session_id=5b7b11ea498eb8b3d5677468

API calls:

http://genomenexus.org/annotation/genomic/19%2C10267171%2C10267171%2CT%2CC?fields=hotspots
http://genomenexus.org/cancer_hotspots/genomic/19%2C10267171%2C10267171%2CT%2CC

**Comment by inodb** [comment]
deployed - is fixed now by making sure the transcript id matches with the transcript id that was used in the algorithm to determine the hotspot
