### ISSUE TITLE
production deployment

### ISSUE THREAD

**Issue by jjgao** [genome-nexus/genome-nexus#22]

**Comment by zheins** [comment]
- [ ] Set up load balanced https tomcat with Joanne
- [x] mongodb set up on dashi
- [ ] testing of tomcat deployment on dashi-dev
- [ ] deploy on dashi
- [ ] point CVR and importer pipelines to deployed genome-nexus on dashi

**Comment by jjgao** [comment]
Sys admin is working on https. Possible sotion: using Amazon.

**Comment by inodb** [comment]
we have a production deployment with https on AWS. We have a separate issue for the k8s deployment
