### ISSUE TITLE
Handle NA reference_allele for some INS

### ISSUE THREAD

**Issue by leexgh** [genome-nexus/genome-nexus#276]
Reference_allele should be `-` but in many studies they are `NA` or multiple `-`.

**Comment by jjgao** [comment]
I guess it doesn't hurt to do this but the data should and will be fixed: https://github.com/cBioPortal/datahub/issues/621

**Comment by leexgh** [comment]
@jjgao That would be great! Thanks! But maybe I can still do it for now, since it doesn't hurt and not so complicated
