### ISSUE TITLE
Refreshing Variant Page Causes 404

### ISSUE THREAD

**Issue by Luke-Sikina** [genome-nexus/genome-nexus#329]
# Overview
When I refresh a page for a variant, it 404s

# Steps
1. Go to genomenexus.org
2. Search for a valid variant: `17:g.41242962_41242963insGA`
3. Hit enter to go to the page
4. Refresh the page  
__Expected behavior:__ the page refreshes
__Observed behavior:__ the page 404s

# Other
I think this is also the case for when someone links to a variant page. I'm guessing this 404s too: https://www.genomenexus.org/variant/17:g.41242962_41242963insGA

**Comment by inodb** [comment]
Thanks a lot for testing! It's related to this one: https://github.com/genome-nexus/genome-nexus/issues/328

**Comment by leexgh** [comment]
see fix https://github.com/genome-nexus/genome-nexus/pull/342
