### ISSUE TITLE
Deploy GENIE Genome Nexus

### ISSUE THREAD

**Issue by averyniceday** [genome-nexus/genome-nexus#357]
Deploy all updates regarding wrapper/server/etc. 

Remember to set chunk size in genome nexus properties (200 would have been the maximum if we were using Ensembl VEP ... but with our VEP wrapper, avoid limited the chunk size)

Coordinate with downstream clients to support updates (such as handling the status field in response records)
- (already handled in code .. just need to rebuild clients)

configure load balancer and domain name in google domains

Done condition : an annotator built with the genie.genomenexus.org web url is able to annotate a maf file

**Comment by sheridancbio** [comment]
Checking domains.google.com .. we see that we had previously set up the DNS name genie.genomenexus.org to route traffic to the ingress loadbalancer node.  What we need to do is to update the ingress rules so that the correct service is used for this domain.

**Comment by averyniceday** [comment]
TODO: 

- [ ] take down testing ig (genie-performance-test and vep-chunk)

- [ ] setup two(?) new instance groups (separate genome-nexus and vep?)

- [ ] start up new mongo on the gn ig

- [ ] start up new VEP with new k8s config (new s3 commands) and new image

- [ ] start up new genome nexus (new chunk size and timeout?)

**Comment by averyniceday** [comment]
Dockerhub images:
**VEP**: `genomenexus/gn-vep:gn-vep-beta`
**Genome Nexus**: `genomenexus/gn-spring-boot:genie-gn-spring-boot-beta`
