### ISSUE TITLE
BRAF has no PTM sites

### ISSUE THREAD

**Issue by jjgao** [genome-nexus/genome-nexus#360]
It seems wrong that BRAF has no PTM site: 

https://www.genomenexus.org/variant/7:g.140453136A%3ET

I couldn't open dbPTM but on UniProt BRAF has a few PTM sites.

https://www.uniprot.org/uniprot/P15056/protvista

**Comment by onursumer** [comment]
I did a quick search on the files we have downloaded from dbPTM (https://github.com/genome-nexus/genome-nexus-importer/tree/53b39dceaff7d69c009340605363954bc2f886fe/data/ptm/input). Seems like there is no reference to either `P15056` or `BRAF_HUMAN`.

We may check if they have a new version of the data once their website is back (I couldn't open it either).

**Comment by jjgao** [comment]
Strange... Maybe that's another reason we should switch to UniProt.

**Comment by onursumer** [comment]
Superseded by #491
