### ISSUE TITLE
Fix version and isoform header duplication

### ISSUE THREAD

**Issue by sheridancbio** [genome-nexus/genome-nexus#363]
The header comments in the annotated maf indicating the genome nexus version and isoform used gets duplicated if they are already present in the input maf being annotated.

example:
```
#isoform: mskcc
#version:  1.0
< DATA>
```

becomes

```
#isoform: mskcc
#version:  1.0
#isoform: mskcc
#version:  1.0
< DATA>
```

**Comment by ao508** [comment]
PR to review: https://github.com/genome-nexus/genome-nexus-annotation-pipeline/pull/121
