### ISSUE TITLE
Response will include all records from request

### ISSUE THREAD

**Issue by sheridancbio** [genome-nexus/genome-nexus#364]
All requests which failed to annotate will be included in the response with a status field indicating failure.

**Comment by sheridancbio** [comment]
Work at the genome-nexus level:
- cache retrieval code already exists (need to look at this)
- notice when VEP-Wrapper has skipped some query records in the response
- add a status member to the response model for all records returned
- "input" member will always be present
- does the current code restore the query order in the response?

**Comment by sheridancbio** [comment]
Thoughts / Design notes:
- when fetching chunks from vep, the fetcher should notice missing responses and insert records to the id2resource map which have the "intput", plus a "vep-failure" status code, and maybe description
- when multiple copies of a variant are present in the query, the response from the genome nexus server should mirror that ... reusing the single query/response interaction with VEP in each position that the record appeared in the request.

**Comment by averyniceday** [comment]
Output should **be in the original order that was sent into Genome Nexus**. Our sort on the GN server level before sending to VEP should be undone before returning response to user.

example output:
[
{
  "id": "1:g.2489252_2489253insC",
  "status": false
},
{
  "id": "2:g.24877752_2477753insA",
  "status": true
  "assembly_name": "GRCh37",
  "seq_region_name": "1",
  "start": 2489253,
  "end": 2489252,
  "allele_string": "-/C",
  "strand": 1,
  ...
},
]
