### ISSUE TITLE
missing gene info for TBC1D3K

### ISSUE THREAD

**Issue by jjgao** [genome-nexus/genome-nexus#374]
and other genes?

Originally reported [here](https://github.com/cBioPortal/cbioportal/issues/1378#issuecomment-408172697)

https://www.cbioportal.org/results/mutations?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=brca_tcga&case_set_id=brca_tcga_cnaseq&data_priority=0&gene_list=TBC1D3K%2520TBC1D3D&geneset_list=%20&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=brca_tcga_gistic&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=brca_tcga_mutations&tab_index=tab_visualize

**Comment by leexgh** [comment]
https://www.cbioportal.org/results/mutations?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=brca_tcga&case_set_id=brca_tcga_cnaseq&data_priority=0&gene_list=TBC1D3K%2520TBC1D3D&geneset_list=%20&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=brca_tcga_gistic&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=brca_tcga_mutations&tab_index=tab_visualize
the above page doesn't have transcript returned, and after checking we found gene TBC1D3K is in the file:
https://github.com/genome-nexus/genome-nexus-importer/blob/master/data/grch37_ensembl92/export/ensembl_biomart_canonical_transcripts_per_hgnc.txt
but TBC1D3K is only in grch38 http://useast.ensembl.org/Homo_sapiens/Gene/Summary?db=core;g=ENSG00000273513;r=17:37924415-37935365;t=ENST00000620247, no results in  grch37 http://grch37.ensembl.org/Homo_sapiens/Search/Results?q=TBC1D3K;site=ensembl;facet_species=Human. 
maybe we could address this issue later if we host grch38?

**Comment by jjgao** [comment]
@leexgh thanks for looking into this.

It looks like there is no mutations at all called for this gene in all tcga studies: https://www.cbioportal.org/results/mutations?Action=Submit&data_priority=0&session_id=5e78e1b6e4b030a3bfcfd879&tab_index=tab_visualize

I am going to close this one.
