### ISSUE TITLE
Fix Bug with Converting to Region Format

### ISSUE THREAD

**Issue by averyniceday** [genome-nexus/genome-nexus#391]
Differences were seen between ENSEMBL VEP and local VEP. 
Comparing queries between hgvs/region endpoints on both VEPS identified a bug with how region format queries are being formed.

It looks like we need to reverse the positions in the query.

Currently we send something like:
- 4:**55593656-55593657**:1/CAACTTCCTTATGATCACAAATGGGAGTTTCCCAGAAACAGGCTGAGTTTTGGT

but we want something like this:
- 4:**55593657-55593656**:1/CAACTTCCTTATGATCACAAATGGGAGTTTCCCAGAAACAGGCTGAGTTTTGGT

**Comment by jjgao** [comment]
cc @inodb

**Comment by inodb** [comment]
That's correct: we found this bug when investigating https://github.com/genome-nexus/genome-nexus/issues/390

**Comment by averyniceday** [comment]
Looked through the code -- looks like this is because the variant is not being registered as an insertion.

The query gets converted from `hgvs` to `GenomicLocation`. However, it does not treat insertion as a special case and sets the ref allele to something like `X` times the length of the query. However, the notationConverter only recognized insertions as GenomicLocations with ref allele `""` or `-` or something similar.
