### ISSUE TITLE
Blank page on this URL: http://grch38.genomenexus.org/variant/7:g.140453136A%3ET

### ISSUE THREAD

**Issue by zhx828** [genome-nexus/genome-nexus#417]
Not sure it is temporary:
![Screen Shot 2020-06-07 at 10 24 41 PM](https://user-images.githubusercontent.com/5400599/83987296-bc79f680-a90d-11ea-8ac1-aefac66cb4a6.png)

But probably the frontend should handle the error?

**Comment by leexgh** [comment]
@zhx828 looks like something related to transcript switch is not handled well, will fix soon. Thanks!

**Comment by inodb** [comment]
not deployed yet, but will be deployed soon. Thanks for reporting!
