### ISSUE TITLE
Some silent mutations are not correct in lollipop

### ISSUE THREAD

**Issue by leexgh** [genome-nexus/genome-nexus#427]
1. sometimes it has `*123*` notation, while sometimes doesn’t 
Has `*123*` notation:
https://www.genomenexus.org/annotation/7:g.140624473C%3ET?fields=annotation_summary 
```
      {
        "transcriptId": "ENST00000469930",
        "entrezGeneId": "673",
        "consequenceTerms": "non_coding_transcript_exon_variant",
        "hugoGeneSymbol": "BRAF",
        "hgvspShort": "p.*13*",
        "hgvsc": "ENST00000469930.1:n.37G>A",
        "variantClassification": "RNA",
        "exon": "1/3"
      },
```

Doesn't have notation:
https://www.genomenexus.org/annotation/7:g.140624473C%3ET?fields=annotation_summary 
```
      {
        "transcriptId": "ENST00000497784",
        "entrezGeneId": "673",
        "consequenceTerms": "upstream_gene_variant",
        "hugoGeneSymbol": "BRAF",
        "variantClassification": "5'Flank"
      }
```

2. some mutations are missing in lollipop (might because the location is larger than the max) 
related to: https://github.com/genome-nexus/genome-nexus/issues/425

3. some mutations are not showing in lollipop even if the location is smaller than the max
https://deploy-preview-3211--cbioportalfrontend.netlify.app/results/mutations?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=msk_impact_2017&case_set_id=msk_impact_2017_cnaseq&data_priority=0&gene_list=BRAF%2520BRCA1&geneset_list=%20&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=msk_impact_2017_cna&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=msk_impact_2017_mutations&mutations_gene=BRCA1&mutations_transcript_id=ENST00000468300&profileFilter=0&tab_index=tab_visualize
Filter by `P-0003370-T01-IM5`

http://localhost:3000/results/mutations?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=msk_impact_2017&case_set_id=msk_impact_2017_cnaseq&data_priority=0&gene_list=BRAF%2520BRCA1&geneset_list=%20&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=msk_impact_2017_cna&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=msk_impact_2017_mutations&mutations_gene=BRAF&mutations_transcript_id=ENST00000479537&profileFilter=0&tab_index=tab_visualize
Filter by only view `Other`

4. some are at the wrong location:
http://localhost:3000/results/mutations?Action=Submit&RPPA_SCORE_THRESHOLD=2.0&Z_SCORE_THRESHOLD=2.0&cancer_study_list=msk_impact_2017&case_set_id=msk_impact_2017_cnaseq&data_priority=0&gene_list=BRAF%2520BRCA1&geneset_list=%20&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=msk_impact_2017_cna&genetic_profile_ids_PROFILE_MUTATION_EXTENDED=msk_impact_2017_mutations&mutations_gene=BRCA1&mutations_transcript_id=ENST00000491747&profileFilter=0&tab_index=tab_visualize
Filter by `P-0004051-T01-IM5`. It's `*263*`, but it shows at around 650

**Comment by inodb** [comment]
@leexgh this is fixed now right?

**Comment by leexgh** [comment]
@inodb should be fixed since we removed hgvspShort for them, but I'm not sure how to explain 3 and 4. Maybe 123 is not the location for *123*?
