### ISSUE TITLE
Replace dbPTM with Uniprot PTM

### ISSUE THREAD

**Issue by onursumer** [genome-nexus/genome-nexus#434]
Replace current dbPTM data with uniprot PTM data.

**Comment by onursumer** [comment]
@jjgao @inodb @leexgh Here is a (customized) table with PTM info that we may want to download and parse:

https://www.uniprot.org/uniprot/?query=keyword:%22PTM%20[KW-9991]%22&fil=organism%3A%22Homo+sapiens+%28Human%29+%5B9606%5D%22+AND+reviewed%3Ayes&sort=score

Note that the Uniprot PTM notation is different than the dbPTM notation. As far as I can see, there is no Phosphorylation, Acetylation, Ubiquitination, etc. But there are notations like Phosphothreonine, N-acetylalanine, etc. Do we want to use these as is, or somehow try to map to the current notation?

**Comment by jjgao** [comment]
Thanks, @onursumer . We should still group them by the PTM type, e.g. Phosphorylation will include phosphoserine/threonine/tyrosine.

**Comment by jjgao** [comment]
Here are the categories of PTMs: https://www.uniprot.org/help/mod_res. You can look for the each keyword for the complete list of mod_res IDs in this file: https://www.uniprot.org/docs/ptmlist

**Comment by onursumer** [comment]
We decided to keep the dbPTM resource for now. We are going to add Uniprot PTM as a separate resource with a different endpoint (see #441).
