### ISSUE TITLE
Mapping from transcript id to uniprot accession

### ISSUE THREAD

**Issue by leexgh** [genome-nexus/genome-nexus#443]
Part of: #440 
Current UniProt endpoints use UniProt accession as key, we want to query PTMs by transcript id as well.

Approach 1: 
- try mapping with UniProt mapping tool with hugo symbols https://www.uniprot.org/uploadlists/
- compare sequences

Approach 2:
- mapping by ccds id. The ccds website has a mapping file and we could use it to map our data

Approach 3:
- mapping by protein sequence: ENSP -> Ensembl sequence = UniProt sequence -> UniProt id
  - Sequence from Ensembl:
    - From api: https://grch37.rest.ensembl.org/sequence/id/ENSP00000288602?content-type=application/json
    - GRCh37: ftp://ftp.ensembl.org/pub/grch37/release-101/fasta/homo_sapiens/pep/
    - GRCh38: ftp://ftp.ensembl.org/pub/release-101/fasta/homo_sapiens/pep/
  - Sequence from UniProt: https://www.uniprot.org/uniprot/?query=+reviewed%3Ayes+AND+organism%3A%22Homo+sapiens+%28Human%29+%5B9606%5D%22&sort=score
- handle multiple UniProt cases
  - Try with bioMart
    - GRCh37: https://grch37.ensembl.org/biomart/martview/145410cb02e693b9da427f9c3dffe61f
    - GRCh38: http://uswest.ensembl.org/biomart/martview/84262bd39b9c7d095757b6ce493a2a9f
    - example query: http://grch37.ensembl.org/biomart/martservice?query=%3C?xml%20version=%221.0%22%20encoding=%22UTF-8%22?%3E%20%3C!DOCTYPE%20Query%3E%20%3CQuery%20%20virtualSchemaName%20=%20%22default%22%20formatter%20=%20%22TSV%22%20header%20=%20%220%22%20uniqueRows%20=%20%220%22%20count%20=%20%22%22%20datasetConfigVersion%20=%20%220.6%22%20%3E%20%3CDataset%20name%20=%20%22hsapiens_gene_ensembl%22%20interface%20=%20%22default%22%20%3E%20%3CFilter%20name%20=%20%22ensembl_peptide_id%22%20value%20=%20%22ENSP00000004921,ENSP00000002165%22/%3E%20%3CAttribute%20name%20=%20%22uniprotswissprot%22%20/%3E%20%3CAttribute%20name%20=%20%22ensembl_peptide_id%22%20/%3E%20%3C/Dataset%3E%20%3C/Query%3E
  - Ensembl xref endpoint: https://grch37.rest.ensembl.org/xrefs/id/ENSP00000289373?content-type=application/json;external_db=Uniprot/SWISSPROT
- mapping result
  - GRCh37: https://github.com/leexgh/genome-nexus-importer/blob/map-transcript-to-accession/scripts/grch37_transcript_to_uniprot_mapping.txt
  - GRCh38: https://github.com/leexgh/genome-nexus-importer/blob/map-transcript-to-accession/scripts/grch38_transcript_to_uniprot_mapping.txt

Todo list:
We are trying with approach 3
- [x] generate transcript to uniprot mapping for [grch37](https://github.com/leexgh/genome-nexus-importer/blob/map-transcript-to-accession/scripts/grch37_transcript_to_uniprot_mapping.txt) and [grch38](https://github.com/leexgh/genome-nexus-importer/blob/map-transcript-to-accession/scripts/grch38_transcript_to_uniprot_mapping.txt)
- [x] check and revise multiple uniprot cases
- [ ] adding uniprot accession to annotation summary response

Once done:
- [ ] adding a new endpoint like `uniprot/features/ensembl/`
- [ ] download or cache Uniprot PTM

Useful links:
- ccds id to sequence map on ccds website: https://ftp.ncbi.nlm.nih.gov/pub/CCDS/current_human/CCDS2Sequence.current.txt

**Comment by leexgh** [comment]
@jjgao @onursumer @inodb I tried the Uniprot mapping tool with grch37 transcripts, some results I got:

1. By using transcript id
53221 out of 100000 Ensembl Transcript identifiers were successfully mapped to 36005 UniProtKB IDs in the table below.
Success rate 53%, might because Uniprot is using grch38. Still not sure why less than 53211 Uniprot ids are mapped. [Link](https://www.uniprot.org/uniprot/?query=yourlist:M202009098471C63D39733769F8E060B506551E12B2FD341&sort=yourlist:M202009098471C63D39733769F8E060B506551E12B2FD341)

2. By using gene id
19852 out of 41303 Ensembl identifiers were successfully mapped to 70791 UniProtKB IDs in the table below.
Success rate 48%. [Link](https://www.uniprot.org/uniprot/?query=yourlist:M202009098471C63D39733769F8E060B506551E12B2FF588&sort=yourlist:M202009098471C63D39733769F8E060B506551E12B2FF588&columns=yourlist(M202009098471C63D39733769F8E060B506551E12B2FF588),isomap(M202009098471C63D39733769F8E060B506551E12B2FF588),id,entry%20name,reviewed,protein%20names,genes,organism,sequence,yourlist(M202009098471C63D39733769F8E060B506551E12B2FD341),isomap(M202009098471C63D39733769F8E060B506551E12B2FD341))

3. By using hugo gene symbol
9584 out of 9694 Gene name identifiers were successfully mapped to 50406 UniProtKB IDs in the table below.
Success rate 98%. Only about 92% of transcripts have gene symbol, not sure if it's ok to ignore them. [Link](https://www.uniprot.org/uniprot/?query=yourlist:M20200909E5A08BB0B2D1C45B0C7BC3B55FD26556B31368A&sort=yourlist:M20200909E5A08BB0B2D1C45B0C7BC3B55FD26556B31368A&columns=yourlist(M20200909E5A08BB0B2D1C45B0C7BC3B55FD26556B31368A),id,entry%20name,reviewed,protein%20names,genes,organism,sequence,yourlist(M202009098471C63D39733769F8E060B506551E12B2FD341),isomap(M202009098471C63D39733769F8E060B506551E12B2FD341))

**Comment by jjgao** [comment]
@leexgh here are the mappings for [grch37](https://docs.google.com/spreadsheets/d/14PN6RtFq_GTAu8OKNUyUNKJ_fj7OlcEhDjbMdapqqo8/edit#gid=133083142) and [grch38](https://docs.google.com/spreadsheets/d/1slDx9zorUuA-xsmH1i9_6CIGjQB1GIgDlWDU5gw6f9I/edit#gid=1399879714) (Final-Mapping tab).

Some numbers:
- For grch37, in total, 27251 ENSTs were mapped 18461 Uniprot IDs
- For grch38, In total, 27846 ENSTs were mapped to 18594 Uniprot IDs

In both versions, there are about 200-300 uniprot IDs that cannot be mapped. Let's not worry about them for now.

**Comment by leexgh** [comment]
@jjgao Thank you so much! Do we need to store the mapping somewhere in genome nexus importer repo?
