### ISSUE TITLE
Adding tri-nucleotide change

### ISSUE THREAD

**Issue by jjgao** [genome-nexus/genome-nexus#444]
Tri-necleotide change is very useful for study mutational signatures. It would be very useful if we can add the tri-nt change to our output. For example, in [this API](https://www.genomenexus.org/annotation/17:g.37880220T%3EC?fields=hotspots%2Cmutation_assessor%2Cmy_variant_info%2Cptms%2Cannotation_summary), add "trinucleotide_context" below "allele_string". 

![image](https://user-images.githubusercontent.com/840895/92814075-8d51a600-f390-11ea-8d3c-e2ea9a5d172d.png)

We can get the sequence from assemble, e.g. https://grch37.rest.ensembl.org/sequence/region/human/17:37880219..37880221:1?content-type=text/plain. It would be good to cache the data.

**Comment by jjgao** [comment]
Looks like we have already implemented it: https://www.genomenexus.org/annotation/17:g.37880220T%3EC?fields=hotspots%2Cmutation_assessor%2Cmy_variant_info%2Cptms%2Cannotation_summary,nucleotide_context

**Comment by inodb** [comment]
Just need to add it here: https://github.com/genome-nexus/genome-nexus-annotation-pipeline
