### ISSUE TITLE
Mutated Issue: Conflicting consequences

### ISSUE THREAD

**Issue by yichaoS** [genome-nexus/genome-nexus#445]
Genome Nexus sometimes gives multiple conflicting consequences (coding vs. non-coding) and 
seems to pick the "coding region" consequence to define variant class
However, wasn't able to find any "coding region" consequence in VEP

For example, this variant in `ccle_broad_2019` was given "coding_sequence_variant","3_prime_UTR_variant" by Genome Nexus (http://annotation.genomenexus.org/hgvs/11:g.5021155_5021163delTTTTAAGTA). However, in VEP we found only "intron" & "regulatory regions" as consequences (https://uswest.ensembl.org/Homo_sapiens/Tools/VEP/Results?tl=7Ip42RfAzFiyQt3E-6543852)
<img width="738" alt="Screen Shot 2020-09-18 at 4 21 42 PM" src="https://user-images.githubusercontent.com/5973438/93641762-d7f3a380-f9ca-11ea-839d-ea261c3687bd.png">

For more examples and complete "mutated" variants stats, please check here:
https://docs.google.com/spreadsheets/d/1RFj8zzMPv4PCAs3sFM9ro3FP4vRg-Za-JI2AFlx6FHg/edit#gid=1944280727

**Comment by sbabyanusha** [comment]
This issue is resolved.
