### ISSUE TITLE
issue with 9:g.21994291C>T

### ISSUE THREAD

**Issue by jjgao** [genome-nexus/genome-nexus#453]
I was looking at [9:g.21994291C>T](https://www.genomenexus.org/variant/9:g.21994291C%3ET) and found multiple issues:

- [x] The variant page of [9:g.21994291C>T](https://www.genomenexus.org/variant/9:g.21994291C%3ET) pick the intron mutation in _RP11-145E5.5_ instead one of the missense mutations in CDKN2A. We should work out the priority list for choosing a default transcript (maybe based on consequence and uniprot canonical isoform?)

    **Answer** The issue in this case is that for the transcript revolver we are still using Ensembl's canonical assignments instead of genome nexus' assignments. https://github.com/genome-nexus/genome-nexus/blob/master/component/src/main/java/org/cbioportal/genome_nexus/component/annotation/CanonicalTranscriptResolver.java#L31-L35. This is why it's picking RP11 (since ensembl labels that as canonical). We do indeed pick most impactful if no canonical is found. Filed a separate issue for this to use the genome nexus canonical assignments:  https://github.com/genome-nexus/genome-nexus/issues/474

- [x] There are two transcripts for CDKN2A in the [mskcc override file](https://github.com/genome-nexus/genome-nexus-importer/blob/8d8d690a66137dff2184cedfefdac01c910bf820/data/isoform_overrides_at_mskcc.txt): `ENST00000304494` (`p16 INK4A`) and `ENST00000361570` (`p14 ARF`). Not sure how we pick a transcript in this case? (There is only one in the [uniprot override file](https://github.com/genome-nexus/genome-nexus-importer/blob/8d8d690a66137dff2184cedfefdac01c910bf820/data/isoform_overrides_uniprot.txt): `ENST00000304494` `p16 INK4A`). Note that p16 should be used as OncoKB is annotating on p16

    **Answer** Currently it picks the first one when there are two (it's picking `ENST00000304494` in this case). See [code](https://github.com/genome-nexus/genome-nexus-importer/blob/ec2789b107fa5894891546d779ab32a51adaee96/scripts/make_one_canonical_transcript_per_gene.py#L14-L15).

    In vcf2maf it works differently, it will pick the most severe effect: https://github.com/mskcc/vcf2maf/issues/263#issuecomment-729956739. Not sure if it makes sense for us to implement the same logic. I imagine it's done this way because `ENST00000304494` spans a short genomic region, whereas `ENST00000361570` spans a longer one. Our current data model assigns one transcript per hugo symbol, so it would be a non-trivial change.

- [x] Somehow, `ENST00000304494` was not annotated in the genome nexus API output. Not sure why?

    **Answer** `ENST00000304494` spans `9: 21,967,752-21,975,097` so 21,994,291 is quite far away from that transcript `CDKN2A-001` spans a short genomic region: http://grch37.ensembl.org/Homo_sapiens/Transcript/Summary?db=core;g=ENSG00000147889;r=9:21967752-21994291;t=ENST00000304494

- [x] [P-0003796](https://cbioportal.mskcc.org/patient?studyId=mskimpact&caseId=P-0003796) in MSK portal has a CDKN2A A55T mutations, but the amino acid 55 on neither p16 nor p14 is A. (The mutation is filtered out in [public portal](https://www.cbioportal.org/patient?studyId=msk_impact_2017&caseId=P-0003796))

    **Answer** this seems to have resolved itself for that patient. I'm guessing after re-annotating. But note that p14 `ENST00000361570.3/ENSP00000355153.3` is actually A at that position:

    ```
    $ curl 'http://grch37.rest.ensembl.org/sequence/id/ENSP00000355153.3?content-type=text/plain' | awk '{print substr($0,55,1)}'
    A
    ```

    When we pick the most severe consequence for `9:g.21994291C>T` `A55T` is actually the correct expected result:

    ```
    "transcript_id": "ENST00000361570",
    "amino_acids": "A/T",
    "protein_start": 55,
    ```

- [ ] Many issues with NSCLC_PD1_MSK2018

**Comment by inodb** [comment]
@jjgao I've answered the various questions (see above). There's one critical issue to follow up on: https://github.com/genome-nexus/genome-nexus/issues/474

I'm not entirely sure what the issues are for `NSCLC_PD1_MSK2018 `: https://bit.ly/3lc2oS0. But maybe better to check once we solve https://bit.ly/3lc2oS0

**Comment by inodb** [comment]
let's close this for now and create new issues as they show up
