### ISSUE TITLE
For picking a transcript use genome nexus canonical assignments, instead of ensembl

### ISSUE THREAD

**Issue by inodb** [genome-nexus/genome-nexus#474]
We are currently using Ensembl's `canonical` field to see what transcripts are canonical: https://github.com/genome-nexus/genome-nexus/blob/master/component/src/main/java/org/cbioportal/genome_nexus/component/annotation/CanonicalTranscriptResolver.java#L31-L35. We should use the info about a transcript being canonical from our assignments: https://github.com/genome-nexus/genome-nexus-importer/blob/master/data/grch37_ensembl92/export/ensembl_biomart_canonical_transcripts_per_hgnc.txt

**Comment by inodb** [comment]
Might need your help with this one at some point @onursumer. One can e.g. add a function like this to get canonical transcript info from the mongo database: https://github.com/inodb/genome-nexus/blob/failed-transcript-consequence-resolver-experiment/persistence/src/main/java/org/cbioportal/genome_nexus/persistence/internal/EnsemblRepositoryImpl.java#L115-L125. But not entirely sure how to get the canoncialtranscriptresolver to use that. It gets a little hairy when I try to move `CanonicalTranscriptResolver` to `service.annotation` such that it can use `EnsemblService` b/c a ton of components depend on `CanonicalTranscriptResolver`

**Comment by onursumer** [comment]
@inodb This probably requires fundamental design change. Current components are not designed to use service or persistence layers. They are more like basic utility classes.

I thought we only needed to override the canonical transcript on the service layer when `isoformOverrideSource` is provided, but looks like it's not the case anymore. We can try adding persistence layer as a dependency to component, and see if it works. In the worst case, we may need to move almost everything from component to service.
