### ISSUE TITLE
VEP unmarshalling refactor

### ISSUE THREAD

**Issue by zheins** [genome-nexus/genome-nexus#49]
Currently, all json responses from VEP are unmarshalled into a String and then transformed into pojos separately. I think it makes more sense to just directly unmarshal into the pojo like [this](https://github.com/cBioPortal/genome-nexus-annotation-pipeline/blob/master/annotator/src/main/java/org/cbioportal/annotator/internal/GenomeNexusImpl.java#L130).

**Comment by onursumer** [comment]
See #75
