### ISSUE TITLE
Work towards "Django inspired" web api

### ISSUE THREAD

**Issue by n1zea144** [genome-nexus/genome-nexus#5]
"meta" json wrapper around subsequent URL to vep_annotation, pfam_annotation, pdb_annotation, etc.

**Comment by inodb** [comment]
@n1zea144 just looking through the open issues. What is this exactly?

**Comment by n1zea144** [comment]
I had HATEOAS in mind when I suggest that.  Provide JSON which includes links back to genome nexus to get subsequent data instead of combining it all into a single JSON.

**Comment by inodb** [comment]
@n1zea144 Ok thanks! Seems Swagger v3 has that: https://blog.readme.io/an-example-filled-guide-to-swagger-3-2/

**Comment by inodb** [comment]
I guess with GraphQL you wouldn't use that, since you would send one object with all the data you want

**Comment by inodb** [comment]
I'm going to close this for now, since we sort of do this by allowing `fields` parameter to get the data that you want. Not as neat as `HATEOAS` but gets the job done. We can maybe revisit this for version 2 of the API
