### ISSUE TITLE
HGVSc blank or error

### ISSUE THREAD

**Issue by leexgh** [genome-nexus/genome-nexus#517]
Report by user: https://groups.google.com/g/cbioportal/c/iO0EHgP7uWY/m/5hF53N2pCwAJ

![image](https://user-images.githubusercontent.com/16869603/117074182-037c9180-ad01-11eb-8518-474df4337e5b.png)
 
The variant with protein change Ile901Serfs*7 is showing as N/A on Genome Nexus (https://www.genomenexus.org/variant/20:g.31023213del)

The curl commands come back as status 200.

Here are the curl calls for the above table that shows ERROR:

curl 'https://v1.genomenexus.org/annotation/genomic?isoformOverrideSource=uniprot&fields=annotation_summary' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0' -H 'Accept: application/json' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://cgen-cbioportal-s.weill.cornell.edu/' -H 'Content-Type: application/json' -H 'Origin: https://cgen-cbioportal-s.weill.cornell.edu' -H 'Connection: keep-alive' --data-raw '[{"chromosome":"20","start":31022415,"end":31022416,"referenceAllele":"AG","variantAllele":"-"},{"chromosome":"20","start":31023213,"end":31023213,"referenceAllele":"C","variantAllele":"-"},{"chromosome":"9","start":5073770,"end":5073770,"referenceAllele":"G","variantAllele":"T"}]'

curl 'https://v1.genomenexus.org/annotation/genomic?isoformOverrideSource=uniprot&fields=annotation_summary&fields=mutation_assessor' -X OPTIONS -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Access-Control-Request-Method: POST' -H 'Access-Control-Request-Headers: content-type' -H 'Referer: https://cgen-cbioportal-s.weill.cornell.edu/' -H 'Origin: https://cgen-cbioportal-s.weill.cornell.edu' -H 'Connection: keep-alive'

curl 'https://v1.genomenexus.org/annotation/genomic?isoformOverrideSource=uniprot&fields=annotation_summary&fields=mutation_assessor' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0' -H 'Accept: application/json' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://cgen-cbioportal-s.weill.cornell.edu/' -H 'Content-Type: application/json' -H 'Origin: https://cgen-cbioportal-s.weill.cornell.edu' -H 'Connection: keep-alive' -H 'TE: Trailers' --data-raw '[{"chromosome":"20","start":31022415,"end":31022416,"referenceAllele":"AG","variantAllele":"-"},{"chromosome":"20","start":31023213,"end":31023213,"referenceAllele":"C","variantAllele":"-"},{"chromosome":"9","start":5073770,"end":5073770,"referenceAllele":"G","variantAllele":"T"}]'

I have noticed that some of the samples with the ERROR yesterday are coming back without the ERROR today. Additionally, it seems like, sometimes, refreshing the page about a minute later will result in the columns being populated and no longer showing ERROR. However, I am still getting this problem of all ERROR in the columns for some samples.

**Comment by leexgh** [comment]
https://www.cbioportal.org/patient?studyId=lgg_ucsf_2014&caseId=P04
HGVSc is blank at first, but if you click header to sort the column or add another column the data will show up

**Comment by inodb** [comment]
CC @onursumer
