### ISSUE TITLE
Annotations Failing (e.g. FGFR3)

### ISSUE THREAD

**Issue by inodb** [genome-nexus/genome-nexus#529]
We noticed last Friday that some annotations for Genome Nexus are failing (see. e.g. FGFR3):

https://app.circleci.com/pipelines/github/genome-nexus/genome-nexus-annotation-pipeline/487/workflows/f1841313-0bac-47ee-ad37-a17c3cc9691e/jobs/699

Wondering if this is due to changes on the server side or in the annotation-pipeline client

**Comment by leexgh** [comment]
It seems like a server side issue, we had this issue since 28days ago https://app.circleci.com/pipelines/github/genome-nexus/genome-nexus-annotation-pipeline/442/workflows/12f4e6ec-32ee-4fb2-9ca4-3836f16d4457/jobs/654

The issue seems related to https://github.com/genome-nexus/genome-nexus/blob/ab72745fd0c15eeb3cccdb303978003f9c62fd9f/service/src/main/java/org/cbioportal/genome_nexus/service/internal/VerifiedGenomicLocationAnnotationServiceImpl.java#L153

**Comment by leexgh** [comment]
igv screenshot: ![Screen Shot 2021-08-05 at 11.14.43 AM.png](https://images.zenhubusercontent.com/5c3d07e393edf60c14e388c8/a9f2d601-dea3-4ba5-9d10-00e171f8d4d2)

**Comment by leexgh** [comment]
our test file:
https://media.githubusercontent.com/media/cBioPortal/datahub/master/public/msk_impact_2017/data_mutations_extended.txt
```
FGFR3			37	4	1806090	1806090			In_Frame_Ins	DEL	A	A	CACT			P-0000056-T01-IM3																	816	370
```

Original file:
https://github.com/cBioPortal/datahub/blob/master/public/msk_impact_2017/data_mutations_extended.txt
```
FGFR3                   GRCh37  4       1806090 1806090 +       protein_altering_variant        In_Frame_Ins    INS     G       A       CACT                    P-0000056-T01-IM3
                                                816     370                     ENST00000260795.2:c.1109delinsCACT      p.Gly370delinsAlaLeu    p.G370delinsAL  ENST00000260795         370     gGc/gCACTc      0
```

**Comment by leexgh** [comment]
In original file Aug 15, 2018:
https://github.com/cBioPortal/datahub/commit/86b834a76d6cecd1f29f65dcb197e4e4e5b4c9bf#diff-726ef2959f70ddf23692199de5fd3c87c2c30c4819443526d85e984ac9db3448
```
FGFR3			37	4	1806090	1806090			In_Frame_Ins	DEL	A	A	CACT			P-0000056-T01-IM3
```

**Comment by inodb** [comment]
Let's maybe summarize the current behavior another time. Just so we are all on the same page

The original source file in datahub has the following annotation:
https://github.com/cBioPortal/datahub/blob/master/public/msk_impact_2017/data_mutations_extended.txt
```
FGFR3                   GRCh37  4       1806090 1806090 +       protein_altering_variant        In_Frame_Ins    INS     G       A       CACT                    P-0000056-T01-IM3
                                                816     370                     ENST00000260795.2:c.1109delinsCACT      p.Gly370delinsAlaLeu    p.G370delinsAL  ENST00000260795         370     gGc/gCACTc      0
```

In CVR it shows up as a frameshift insertion:

<img width="1014" alt="Screen Shot 2021-09-14 at 1 41 04 PM" src="https://user-images.githubusercontent.com/1334004/133307134-38302d20-5817-4343-bb96-8fd10b9ccedb.png">
<img width="983" alt="Screen Shot 2021-09-14 at 1 40 58 PM" src="https://user-images.githubusercontent.com/1334004/133307136-8f8859ac-5283-4073-b57a-5c9cf08d4d51.png">

In our latest updates for genome nexus it will only show the missense mutation with the given input file since tumor seq allele 1 differs from the ref seq allele

**Comment by inodb** [comment]
Let's change `Tumor_Seq_Allele1` to `G` as well like the `Reference_Allele`
