### ISSUE TITLE
NOTCH1:c.1586_1587dup doesn't work

### ISSUE THREAD

**Issue by inodb** [genome-nexus/genome-nexus#542]
Ensembl gives a response:

https://grch37.rest.ensembl.org/variant_recoder/human/NOTCH1:c.1586_1587dup?content-type=application/json

Which indicates there are multiple genomic locations possible:

`Possible invalid use of gene or protein identifier 'NOTCH1' as HGVS reference; NOTCH1:c.1586_1587dup may resolve to multiple genomic locations`

But it only gives one possible option:

`"NC_000009.11:g.139410515_139410516insCA"`

which goes to:

https://www.genomenexus.org/variant/9:g.139410515_139410516insCA

So maybe even with the warning we should try to list all options?

**Comment by leexgh** [comment]
@inodb It has similar warning for [BRAF V600E](https://grch37.rest.ensembl.org/variant_recoder/human/BRAF:p.V600E?content-type=application/json):
```
Possible invalid use of gene or protein identifier 'BRAF' as HGVS reference; BRAF:p.V600E may resolve to multiple genomic locations
```
