### ISSUE TITLE
Investigate why IKBKE variant has no exon

### ISSUE THREAD

**Issue by leexgh** [genome-nexus/genome-nexus#569]
https://www.genomenexus.org/variant/1:g.206646599A%3ET

**Comment by leexgh** [comment]
We get exon information from GFF file: ftp://ftp.ensembl.org/pub/grch37/release-92/gff3/homo_sapiens/Homo_sapiens.GRCh37.87.gff3.gz
https://github.com/genome-nexus/genome-nexus-importer/blob/master/scripts/transform_gff_to_tsv_for_exon_info_from_ensembl.py#L30
But there is no exon info for IKBKE in this GFF file

**Comment by inodb** [comment]
Looks like this is part of MSK-IMPACT panel so we can't change the canonical transcript
