### ISSUE TITLE
Python API client issue

### ISSUE THREAD

**Issue by haochenz96** [genome-nexus/genome-nexus#598]
Hello,

I followed the instructions in the [notebook](https://github.com/genome-nexus/genome-nexus/blob/master/notebooks/genome_nexus_python_example.ipynb) to connect to the API in Python, but the command:
```
client = SwaggerClient.from_url('https://www.genomenexus.org/v2/api-docs',
                                config={"validate_requests":False,"validate_responses":False})
```

returned ValidationError (see attached screenshot). I was wondering if this is caused by any incompatibility between the Bravado client reader and your API? 

Thanks!

<img width="803" alt="Screen Shot 2022-02-26 at 6 32 23 PM" src="https://user-images.githubusercontent.com/54121237/155865944-bd4b2160-ff5a-471f-a1c3-af4d59c6cf3c.png">
<img width="808" alt="Screen Shot 2022-02-26 at 6 32 06 PM" src="https://user-images.githubusercontent.com/54121237/155865945-a50d9ea0-0978-40cc-a541-dc4400ecf810.png">

**Comment by leexgh** [comment]
@haochenz96 Hello, this issue is fixed, please see the latest notebook: https://github.com/genome-nexus/genome-nexus/blob/master/notebooks/genome_nexus_python_example.ipynb
