### ISSUE TITLE
Get PFAM domain name, description, and color

### ISSUE THREAD

**Issue by onursumer** [genome-nexus/genome-nexus#61]
Find a service to get the domain name, description and color for a given PFAM domain id (such as PF00146, PF06444, etc).

PFAM database might be useful for this: http://pfam.xfam.org/help#tabview=tab12

**Comment by jjgao** [comment]
This is probably enough:

http://pfam.xfam.org/family/PF02171/id?output=xml

More detailed version would be this:

http://pfam.xfam.org/family/PF02171?output=xml

**Comment by onursumer** [comment]
@jjgao This endpoint works for name & description, but we still miss the color information.

Also we have to query one PFAM id at a time, because this endpoint does not support multiple queries. Querying the endpoint multiple times is still okay though, since we only need to do it once at the back end. We are fine as long as we are not blocked due to too many queries :)

**Comment by jjgao** [comment]
@onursumer we can also try to get a dump of all pfam domain info and cache them. Do we need to assign our own color?

**Comment by onursumer** [comment]
@jj I think all the PFAM family/domain information we need is in this file: ftp://ftp.ebi.ac.uk/pub/databases/Pfam/releases/Pfam31.0/database_files/pfamA.txt.gz

We may need to assign our own colors. I was not able to find the color information anywhere in their database. Maybe they are dynamically generating those colors within their software, or getting them from some other source.

**Comment by jjgao** [comment]
@onursumer OK to assign our own colors. Make sure they assigned consistently. Maybe we can get all PFAM domains and assign the colors and save them into a text file? Maybe we should save PFAM info in a text file with the following columns / attributes: `PFAM_ID`, `NAME`, `DESCRIPTION`, `COLOR`?

**Comment by onursumer** [comment]
@jjgao The text file mentioned above already has pfam id, name and description info. The only missing thing is color. We can just extend that file by adding the colors.

Also @inodb sent an email to PFAM team to ask if they have the color mappings available for download. If they don't have it, then we can assign our own colors.

**Comment by onursumer** [comment]
After a little inspection of the PFAM graphic endpoint, I figured out that they always use the same color scheme. They always assign same colors for each sequence. First domain in the sequence gets `#2dcf00`, second one gets `#ff5353`, and so on. Here are the first 15 colors:
```
[#2dcf00, #ff5353, #5b5bff, #ebd61d, #ba21e0, #ff9c42, #ff7dff, #b9264f, #baba21, #c48484, #1f88a7, #cafeb8, #4a9586, #ceb86c, #0e180f]
```

**Comment by inodb** [comment]
@onursumer i guess they only made the endpoint so they can replace it with something more sophisticated later on?

**Comment by onursumer** [comment]
@inodb I am not sure if they intend to replace it ever :)

They also have shapes assigned to each domain, which we don't use. We always display rectangles with assigned colors. Their graphics are a bit fancier, as opposed to our simple representation.

**Comment by jjgao** [comment]
@onursumer I see. Good detective work! So colors of the same domain may change in different proteins?

**Comment by onursumer** [comment]
@jjgao Seems like that's the case. I didn't look for an example to confirm that though.

**Comment by jjgao** [comment]
Confirmed -- see below. In this case, since nobody has complained about it, let's do the same thing. Maybe this logic should be implemented in MutatonMapper?

![image](https://user-images.githubusercontent.com/840895/30983450-7fa67204-a458-11e7-882c-8d17b3a6fefd.png)

![image](https://user-images.githubusercontent.com/840895/30983460-875afbf0-a458-11e7-9e5f-66b9c5e9b5c3.png)

**Comment by onursumer** [comment]
@jjgao Thanks for confirming! Yes, I think it is better to implement coloring in mutation mapper, not in genome nexus.
