### ISSUE TITLE
Set up genome nexus documentDB 

### ISSUE THREAD

**Issue by leexgh** [genome-nexus/genome-nexus#624]
The current database only has one primary instance, there is no backup when it crushes. 
Goal: Set up genome nexus documentDB to have replica settings.

Tasks:
- [x] Create documentDB cluster
- [x] Connect to documentDB
- [x] Dump all data from current genome nexus database
- [ ] Test (index, cache, etc...)
- [x] Connect documentDB with app

**Comment by leexgh** [comment]
Issue: After connecting to documentdb, the app compiling is always stuck at signal index building.
I did some tests and noticed the most time-consuming process is [findByVariantIn](https://github.com/genome-nexus/genome-nexus/blob/master/service/src/main/java/org/cbioportal/genome_nexus/service/internal/SignalQueryServiceImpl.java#L83)
I switch genome nexus app to documentDB to test the performance of `findByVariantIn` with 50000 variants (signal has 110000 variants but it reaches the timeout limit so reduce to 50000 for testing purpose). Here is the results comparing with original MongoDB:
| database | number of variants | average time |
| -- | -- | -- |
| MongoDB | 50000 | 20s |
| DocumentDB | 50000 | 4min30sec |

**Comment by inodb** [comment]
decided to look into k8s again, since the performance was not great for documentdb
