### ISSUE TITLE
Missing transcripts for H2BC17 

### ISSUE THREAD

**Issue by leexgh** [genome-nexus/genome-nexus#654]
https://v1.genomenexus.org/ensembl/canonical-transcript/hgnc/H2BC17?isoformOverrideSource=mskcc
Returns 404 because we don't have transcript info for H2BC17.
To be more specific, from [ensembl_biomart_canonical_transcripts_per_hgnc.txt](https://github.com/genome-nexus/genome-nexus-importer/blob/master/data/grch37_ensembl92/export/ensembl_biomart_canonical_transcripts_per_hgnc.txt) we can find canonical transcript for H2BC17 is ENST00000616182
```
hgnc_symbol ... mskcc_canonical_transcript
H2BC17 ... ENST00000616182
```
But ENST00000616182 doesn't exist in [ensembl_biomart_transcripts.json.gz](https://github.com/genome-nexus/genome-nexus-importer/blob/master/data/grch37_ensembl92/export/ensembl_biomart_transcripts.json.gz), so we don't have annotation for this transcript

**Comment by inodb** [comment]
this hugo symbol is only in grch38
