### ISSUE TITLE
feature : bypass_cache parameter to force hgvs web service to compute annotations

### ISSUE THREAD

**Issue by sheridancbio** [genome-nexus/genome-nexus#69]
The hgvs annotation service will deliver results from cache if the response is in the mongoDB cache. However, for performing tests on this genome nexus service, it would be convenient to allow the client to request a variation be computed from scratch, ignoring any value in the cache. Perhaps with a parameter such as "&bypass_cache=true" or "&ignore_cache=true". If not supplied, this parameter should default to false.

While adding this feature, perhaps also consider enabling the server to replace values in the cache if re-computation using VEP yields a different [and valid] response. This behavior might be requested by the client with a parameter such as &invalidate_cached_value=true.

**Comment by inodb** [comment]
@sheridancbio actually briefly discussed this with @jjgao  and @onursumer today. We think this "backdoor" might lead to overuse of that parameter. 

We should def have some way to invalidate/update the cache, either through some cron jobs or using an API endpoint, but we think this should be solved by maintainers of the system (ideally in an automated fashion) instead of the client.

**Comment by jjgao** [comment]
Supporting tests and debugging might be a valid use case, but I think we should not make this option available to other users.

**Comment by sheridancbio** [comment]
I agree that the potential for abuse by the public / attackers is a concern. Maybe an alternative would be to have some authenticated API endpoints to allow properly authorized people to query / manage / expire / clear items from the mongo cache.

**Comment by jjgao** [comment]
@sheridancbio maybe that can be done in a separate project/repo/war, e.g. genome-nexus-manager?

**Comment by sheridancbio** [comment]
I think that's a really good idea @jjgao .. that way the manager/testing web application can be running on an internal machine without any public access.

**Comment by onursumer** [comment]
@jjgao @sheridancbio Separating the manager app from the API is a very good idea. I think a separate module is a better idea than a separate repo. We can simply add a new `manager` module to seamlessly reuse our existing modules (`model`, `persistence`,  and `service`).

**Comment by inodb** [comment]
looks like we're going for a different approach than the one proposed in this issue
