### ISSUE TITLE
Different response in POST /annotation/genomic and GET /annotation/genomic/{genomicLocation}

### ISSUE THREAD

**Issue by leexgh** [genome-nexus/genome-nexus#708]
Error message for same variant differs.
**POST /annotation/genomic**
```
[
  {
    "chromosome": "17",
    "start": 63010911,
    "end": 63010911,
    "referenceAllele": "A",
    "variantAllele": "G"
  }
]
```
response:
```
[
  {
    "variant": "17:g.63010911A>G",
    "errorMessage": "Reference allele extracted from response (-) does not match given reference allele (A)",
    "originalVariantQuery": "17,63010911,63010911,A,G",
    "successfully_annotated": false
  }
]
```
**GET /annotation/genomic/{genomicLocation}**
```
17,63010911,63010911,A,G
```
response:
```
{
  "variant": "17:g.63010911A>G",
  "errorMessage": "Unable to parse HGVS notation '17:g.63010911A>G': Reference allele extracted from 17:63010911-63010911 (T) does not match reference allele given by HGVS notation 17:g.63010911A>G (A)",
  "originalVariantQuery": "17,63010911,63010911,A,G",
  "successfully_annotated": false
}
```

**Comment by dassudip2001** [comment]
I am interested in fixing this issue if it pending

**Comment by leexgh** [comment]
@dassudip2001 Thanks for your interest in fixing this! I have a draft fix PR here: https://github.com/genome-nexus/genome-nexus/pull/709. It's not a perfect solution, ideally it should be able to show the detailed error message (e.g., 'Unable to parse HGVS notation...') instead of manually putting general information like 'Error from VEP...'. Feel free to create a PR if you have other ideas for fixing it.
