### ISSUE TITLE
Create automated docker image for annotation-tools

### ISSUE THREAD

**Issue by inodb** [genome-nexus/genome-nexus#731]
The docker image already exists:

https://github.com/genome-nexus/annotation-tools

Let's push this image through github actions. Maybe we can then also update the instructions here to use the Docker image (as an alternative to system Python): https://docs.genomenexus.org/annotate-vcf-file

Can use similar github action to this: https://github.com/genome-nexus/genome-nexus/blob/master/.github/workflows/publish_docker_image.yml

There is an unofficial image that you should be able to use in the meantime:

https://hub.docker.com/repository/docker/edit01/annotation-tools/general

**Comment by aishikanandi** [comment]
Hi @inodb, I wanted to confirm if this issue is already fixed using pull request [#61](https://github.com/genome-nexus/annotation-tools/actions/workflows/publish_docker_image.yml)

**Comment by hweej** [comment]
Sorry for the delayed response @aishikanandi. Yes! Closing this issue...
